# -*- dockerfile -*-

ARG BASE=docker.io/nvidia/cuda:12.8.1-devel-ubuntu22.04

FROM $BASE

ARG GDRCOPY_VER=2.3

RUN apt-get update && \
    apt-get install -y autoconf libtool git wget libhwloc-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install NVIDIA gdrcopy
RUN git clone --depth=1 -b v${GDRCOPY_VER} https://github.com/NVIDIA/gdrcopy.git && \
    cd gdrcopy && \
    export CUDA_PATH=${CUDA_HOME:-$(echo $(which nvcc) | grep -o '.*cuda')} && \
    make CC=gcc CUDA=$CUDA_PATH lib && \
    make lib_install && \
    cd ../ && rm -rf gdrcopy

ENV JULIA_DEPOT_PATH=/usr/local/julia_depot
ENV JULIAUP_DEPOT_PATH=/usr/local/julia

# Install Juliaup
RUN wget -O install.sh https://install.julialang.org && \
    chmod +x ./install.sh && \
    ./install.sh --yes --path /usr/local/julia --default-channel 1.11.7

ENV PATH=/usr/local/julia/bin:$PATH

RUN julia -E 'Base.current_image_targets()'
RUN julia -E 'Base.DEPOT_PATH'

# # First installation of the environment. In this iteration we only want to set the
# # preference for `CUDA_Runtime_jll`, contained in the `LocalPreferences-base.toml` file,
# # because the `Reactant_jll` build with CUDA is way larger and would take an awful lot of
# # time to push to the remote registry.  This is unideal, wouldn't have this concern with a
# # single container setup.
# COPY LocalPreferences-base.toml /LocalPreferences.toml
# RUN git clone --depth=1 https://github.com/PRONTOLab/GB-25 && \
#     cd GB-25 && \
#     export JULIA_DEBUG="Reactant_jll" && \
#     mv /LocalPreferences.toml . && \
#     julia --project -O2 -e 'using Pkg; Pkg.instantiate()' && \
#     cd ../ && \
#     rm -rf GB-25


# -------------------------------
# -------------------------------
# # syntax=docker/dockerfile:1
# ARG BASE_IMAGE_TAG
# FROM $BASE_IMAGE_TAG

# We *must* install the `GordonBell25` package in the same directory as where it is on the
# host machine, because the path will be used at runtime to retrieve the precompile cache:
# using a different path would invalidate the cache making this effort wasted.
ARG DESTDIR

RUN mkdir -pv $DESTDIR

# Copy over the local environment, together with the source code and everything.
# assumes you have Manifest.toml locally
COPY Manifest.toml $DESTDIR/Manifest.toml
COPY Project.toml $DESTDIR/Project.toml
# This time we use `LocalPreferences.toml` file to enable CUDA support in `Reactant_jll`,
# because that's what we eventually need.
COPY container-perlmutter/LocalPreferences.toml /usr/local/julia_depot/environments/v1.11/LocalPreferences.toml
COPY src $DESTDIR/src
COPY ext $DESTDIR/ext

# Add the global environment to the global path to make sure the preference file we put
# there takes effect...
ENV JULIA_LOAD_PATH=/usr/local/julia_depot/environments/v1.11:
# ...and "install" `CUDA_Runtime_jll` and `Reactant_jll`, that's necessary too.
RUN export JULIA_DEBUG="Reactant_jll" && \
    export JULIA_PKG_PRECOMPILE_AUTO="false" && \
    export LD_LIBRARY_PATH="/usr/local/cuda-12.8/compat:${LD_LIBRARY_PATH}" && \
    julia -e 'using Pkg; Pkg.add(["CUDA_Runtime_jll", "Reactant_jll"])'

# Finally instantiate the environment.
RUN export JULIA_DEBUG="Reactant_jll" && \
    export LD_LIBRARY_PATH="/usr/local/cuda-12.8/compat:${LD_LIBRARY_PATH}" && \
    julia --project=$DESTDIR -O2 -e 'using Pkg; Pkg.instantiate()'

# Cleanup.
RUN rm -rfv $DESTDIR
